run:
  deadline: 6m
  skip-dirs:
    - terst
  skip-files:
    - dbg/dbg.go
    - token/token_const.go

linters-settings:
  govet:
    check-shadowing: false
  goconst:
    min-len: 2
    min-occurrences: 4
  revive:
    enable-all-rules: false
    rules:
    - name: var-naming
      disabled: true

linters:
  enable-all: true
  disable:
    - dupl
    - lll
    - gochecknoglobals
    - gochecknoinits
    - scopelint
    - funlen
    - godox
    - exhaustivestruct
    - goerr113
    - wsl
    - nlreturn
    - gomnd
    - paralleltest
    - wrapcheck
    - testpackage
    - gocognit
    - nestif
    - exhaustive
    - forcetypeassert
    - gocyclo
    - cyclop
    - varnamelen
    - maintidx
    - ireturn
    - exhaustruct
    - nosnakecase
    - dupword
    - structcheck
    - deadcode
    - golint
    - varcheck
    - ifshort
    - interfacer
    - maligned
    # Just causes noise
    - depguard

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude:
  - Deferring unsafe method "Close" on type "io\.ReadCloser"
